export const initialCMSData = {
  hero: {
    title: 'Litros & Litros',
    subtitle: 'Donde la música, la gastronomía y la diversión se encuentran en Puebla',
    btn1: 'Ver menú',
    btn2: 'Reservar karaoke',
    logo: 'https://horizons-cdn.hostinger.com/a11fab72-8fa1-435a-81fd-8c8f92a5a284/176ad26295791c3dbb5a84904bb2322a.jpg',
  },
  cta: {
    title: '¿Listo para cantar y disfrutar?',
    sub: 'Reserva tu mesa o turno de karaoke ahora mismo',
    btn: 'Contáctanos ahora',
  },
  contact: {
    address: 'Blvd Héroes del 5 de Mayo 4610, Santa María, 72080 Heroica Puebla de Zaragoza, Pue.',
    phone: '+52 222 430 2693',
    email: 'info@litrosylitros.com',
    hours: 'Lunes a Domingo: 18:00 – 02:00',
    wa: '522224302693',
  },
  footer: {
    brand: 'Litros & Litros',
    desc: 'El mejor bar de karaoke en Puebla. Disfruta de música, gastronomía y diversión en un ambiente único.',
    copyright: '© 2026 Litros & Litros. Todos los derechos reservados.',
  },
  socials: {
    fb: 'https://www.facebook.com/profile.php?id=61587845141536',
    ig: 'https://instagram.com',
    tt: '',
    yt: '',
  },
  about: {
    title: 'Nuestra historia',
    sub: 'Más que un bar, somos una familia que celebra la música y la buena compañía',
    h2: 'Desde 2018 en el corazón de Puebla',
    img: 'https://images.unsplash.com/photo-1502158817207-08ef5c149b03?w=800&h=600&fit=crop',
    p1: 'Litros & Litros nació de la pasión por crear un espacio donde la música, la gastronomía y la diversión se encuentran. Desde nuestros inicios, hemos sido el punto de encuentro favorito para quienes buscan una noche inolvidable.',
    p2: 'Nuestro equipo trabaja cada día para ofrecer la mejor experiencia: desde nuestros bartenders expertos hasta nuestros chefs que preparan platillos auténticos mexicanos.',
    p3: 'Con más de 2,000 canciones en nuestro catálogo de karaoke y eventos semanales, nos hemos convertido en el destino preferido para celebrar, cantar y disfrutar en Puebla.',
  },
  seo: {
    title: 'Litros & Litros - Bar de Karaoke en Puebla',
    desc: 'El mejor bar de karaoke en Puebla.',
    kw: 'bar karaoke puebla, litros y litros',
  },
  menuData: {
    food: [
      { id: 1, name: 'Tacos al Pastor', price: '$89.00', description: 'Tres tacos con carne marinada, piña, cilantro y cebolla', image: 'https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=400&h=300&fit=crop', category: 'Antojitos', featured: false },
      { id: 2, name: 'Alitas BBQ', price: '$129.00', description: 'Doce alitas crujientes con salsa BBQ casera', image: 'https://images.unsplash.com/photo-1608039755401-742074f0548d?w=400&h=300&fit=crop', category: 'Botanas', featured: false },
      { id: 3, name: 'Nachos Supremos', price: '$149.00', description: 'Nachos con queso fundido, jalapeños, guacamole y crema', image: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=400&h=300&fit=crop', category: 'Botanas', featured: true },
      { id: 4, name: 'Hamburguesa Litros', price: '$159.00', description: 'Carne angus, queso cheddar, tocino, cebolla caramelizada', image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop', category: 'Platillos', featured: false },
    ],
    drinks: [
      { id: 5, name: 'Margarita Clásica', price: '$89.00', description: 'Tequila, triple sec, limón fresco, sal en el borde', image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop', category: 'Cocteles', featured: false },
      { id: 6, name: 'Michelada Preparada', price: '$69.00', description: 'Cerveza clara, limón, sal, chamoy y salsas especiales', image: 'https://images.unsplash.com/photo-1618183479302-1e0aa382c36b?w=400&h=300&fit=crop', category: 'Cervezas', featured: true },
      { id: 7, name: 'Mojito de Menta', price: '$95.00', description: 'Ron blanco, menta fresca, limón, azúcar y agua mineral', image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=400&h=300&fit=crop', category: 'Cocteles', featured: false },
      { id: 8, name: 'Mezcal Artesanal', price: '$119.00', description: 'Mezcal de Oaxaca con naranja y sal de gusano', image: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=400&h=300&fit=crop', category: 'Destilados', featured: false },
    ],
  },
  songs: [
    { id: 1, title: 'Bohemian Rhapsody', artist: 'Queen', genre: 'Rock', language: 'Inglés' },
    { id: 2, title: 'Bésame Mucho', artist: 'Consuelo Velázquez', genre: 'Bolero', language: 'Español' },
    { id: 3, title: "Livin' on a Prayer", artist: 'Bon Jovi', genre: 'Rock', language: 'Inglés' },
    { id: 4, title: 'La Bamba', artist: 'Ritchie Valens', genre: 'Rock', language: 'Español' },
    { id: 5, title: "Don't Stop Believin'", artist: 'Journey', genre: 'Rock', language: 'Inglés' },
    { id: 6, title: 'Cielito Lindo', artist: 'Tradicional', genre: 'Mariachi', language: 'Español' },
    { id: 7, title: "Sweet Child O' Mine", artist: "Guns N' Roses", genre: 'Rock', language: 'Inglés' },
    { id: 8, title: 'Amor Eterno', artist: 'Juan Gabriel', genre: 'Balada', language: 'Español' },
    { id: 9, title: 'I Will Survive', artist: 'Gloria Gaynor', genre: 'Disco', language: 'Inglés' },
    { id: 10, title: 'El Rey', artist: 'José Alfredo Jiménez', genre: 'Ranchera', language: 'Español' },
    { id: 11, title: 'Wonderwall', artist: 'Oasis', genre: 'Rock', language: 'Inglés' },
    { id: 12, title: 'Vivir Mi Vida', artist: 'Marc Anthony', genre: 'Salsa', language: 'Español' },
  ],
  karaokeDates: [
    { id: 1, date: '2026-06-05', theme: 'Jueves de Rock Clásico', time: '20:00' },
    { id: 2, date: '2026-06-06', theme: 'Viernes de Baladas Románticas', time: '21:00' },
    { id: 3, date: '2026-06-07', theme: 'Sábado de Éxitos Pop', time: '22:00' },
    { id: 4, date: '2026-06-12', theme: 'Jueves de Rancheras y Mariachi', time: '20:00' },
    { id: 5, date: '2026-06-13', theme: 'Viernes de Reggaeton y Urbano', time: '21:00' },
    { id: 6, date: '2026-06-14', theme: 'Sábado de Rock en Español', time: '22:00' },
  ],
  events: [
    { id: 1, title: 'Noche de Rock en Español', date: '2026-06-06', time: '21:00', description: 'Los mejores clásicos del rock en español con banda en vivo', image: 'https://images.unsplash.com/photo-1502158817207-08ef5c149b03?w=600&h=400&fit=crop', price: '$150.00', featured: true },
    { id: 2, title: 'Fiesta de los 80s y 90s', date: '2026-06-13', time: '22:00', description: 'Revive las mejores canciones de dos décadas inolvidables', image: 'https://images.unsplash.com/photo-1662062164619-24e430ac9f40?w=600&h=400&fit=crop', price: '$120.00', featured: false },
    { id: 3, title: 'Karaoke Battle Championship', date: '2026-06-20', time: '20:00', description: 'Competencia de karaoke con premios en efectivo', image: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600&h=400&fit=crop', price: '$100.00', featured: true },
    { id: 4, title: 'Noche de Salsa y Cumbia', date: '2026-06-27', time: '21:30', description: 'Baila toda la noche con los mejores ritmos latinos', image: 'https://images.unsplash.com/photo-1547153760-18fc86324498?w=600&h=400&fit=crop', price: '$130.00', featured: false },
  ],
}
